server.port=${SERVER_PORT:8080}

# Application name
spring.application.name=${SPRING_APPLICATION_NAME:evantra}

# Supabase PostgreSQL database connection settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.mcnmeastlbjepyzfiipa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Kubernetes@23}

spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:5}
spring.datasource.hikari.data-source-properties.prepareThreshold=${SPRING_DATASOURCE_PREPARE_THRESHOLD:0}
spring.datasource.hikari.data-source-properties.cachePrepStmts=${SPRING_DATASOURCE_CACHE_PREP_STMTS:false}
spring.datasource.hikari.data-source-properties.useServerPrepStmts=${SPRING_DATASOURCE_USE_SERVER_PREP_STMTS:false}

# Hibernate / JPA settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# Optional: Show SQL statements in console
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
spring.jpa.open-in-view=${SPRING_JPA_OPEN_IN_VIEW:false}

# JWT Secret Key for signing tokens (change this to a long, random string in production)
jwt.secret=${JWT_SECRET:s9dF+X3qP8y7Wz1JkL0VnT6rQm2bE4pHfYvR8uC1aS0=}

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:eventra.evana@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:eqglhqaqsnnvdgsk}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS_ENABLE:true}

razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_ROwwkhH18vuUPJ}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:ioZKLYVFCRB7mr119PkSpzlH}
