# Application name
spring.application.name=evantra

# Supabase PostgreSQL database connection settings
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.mcnmeastlbjepyzfiipa
spring.datasource.password=Kubernetes@23

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.useServerPrepStmts=false

# Hibernate / JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Show SQL statements in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT Secret Key for signing tokens (change this to a long, random string in production)
jwt.secret=s9dF+X3qP8y7Wz1JkL0VnT6rQm2bE4pHfYvR8uC1aS0=

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eventra.evana@gmail.com
spring.mail.password=eqglhqaqsnnvdgsk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.key.id=rzp_test_ROwwkhH18vuUPJ
razorpay.key.secret=ioZKLYVFCRB7mr119PkSpzlH